kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-amd64
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-ppc64le
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod-amd64
spec:
  containers:
  - name: test-pod-amd64
    image: docker.io/library/busybox:stable
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim-amd64
  securityContext:
    seccompProfile: 
      type: RuntimeDefault
    runAsNonRoot: true
    capabilities:
      drop:
      - all
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
  nodeSelector:
    kubernetes.io/arch: amd64
    node.openshift.io/os_id: rhcos
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod-ppc64le
spec:
  containers:
  - name: test-pod-ppc64le
    image: docker.io/library/busybox:stable
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim-ppc64le
  securityContext:
    seccompProfile: 
      type: RuntimeDefault
    runAsNonRoot: true
    capabilities:
      drop:
      - all
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
  nodeSelector:
    kubernetes.io/arch: ppc64le
    node.openshift.io/os_id: rhcos