---
- block:
    - assert: 
        that: "{{ helper.networkifacename is defined }}"
        msg: "helper.networkifacename is not defined"
    - set_fact: 
        networkifacename: "{{ helper.networkifacename }}"
  rescue:
    - set_fact:
        networkifacename: "{{ ansible_default_ipv4.interface }}"

- block:
  - set_fact:
      critical_services:
        - httpd
        - named
        - dhcpd

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - httpd
        - vim
        - bash-completion
        - libselinux-python
        - podman
        - nfs-utils
        - dhcp
        - tftp-server
        - git
        - dhcpd
        - bind-utils

  - set_fact:
      services:
        - named
        - httpd
        - rpcbind
  when: ansible_distribution_major_version == "7"

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - httpd
        - vim
        - bash-completion
        - python3-libselinux
        - podman
        - nfs-utils
        - grub2-tools
        - grub2-tools-extra
        - bind-utils
  
  - set_fact:
      dhcppkgs:
        - dhcp-server
        - tftp-server

  # See Fedora Wiki for changes:
  # https://fedoraproject.org/wiki/Changes/RenameNobodyUser
  - set_fact:
      owner: nobody
      group: nobody
  
  - set_fact:
      services:
        - named
        - httpd
        - rpcbind
        - nfs-server
  when: ansible_distribution_major_version >= "8"
