galaxy_info:
  author: Chandan Abhyankar
  description: Enables support operations for day-2 installation
  company: IBM
  license: Apache-2.0
  min_ansible_version: 2.12.0

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags: []

dependencies: []
