apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ "auto-nfs-storage" if cicd|lower == "true" else "nfs-storage" }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  onDelete: delete
  archiveOnDelete: "false"
