---
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp-dev-preview/4.14.0-ec.3/ppc64le/openshift-client-linux.tar.gz"
openshift_machine_config_url: "https://<HOSTNAME>:22623/config/worker"
vpc_support_machine: "<IP>"
ports:
- 67/udp
- 68/udp
- 53/tcp
- 53/udp
- 8080/tcp
- 6443/tcp
- 6443/udp
- 22623/tcp
- 22623/udp
- 9000/tcp
- 69/udp
- 111/tcp
- 2049/tcp
- 20048/tcp
- 50825/tcp
- 53248/tcp
